#pragma once
#include <ntddk.h>

#define IIDA_DEVICE_TYPE 0x8000

#define IOCTL_READ_KERNEL_MEMORY  CTL_CODE(IIDA_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GET_MODULE_LIST     CTL_CODE(IIDA_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_GET_MODULE_BASE     CTL_CODE(IIDA_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS)

#pragma pack(push, 1)

typedef struct _READ_KERNEL_REQUEST {
    ULONG64 Address;
    ULONG   Size;
} READ_KERNEL_REQUEST, *PREAD_KERNEL_REQUEST;

typedef struct _MODULE_ENTRY {
    ULONG64 Base;
    ULONG   Size;
    CHAR    Name[64];
    CHAR    Path[256];
} MODULE_ENTRY, *PMODULE_ENTRY;

typedef struct _MODULE_LIST_HEADER {
    ULONG Count;
} MODULE_LIST_HEADER, *PMODULE_LIST_HEADER;

typedef struct _MODULE_BASE_REQUEST {
    CHAR Name[64];
} MODULE_BASE_REQUEST, *PMODULE_BASE_REQUEST;

typedef struct _MODULE_BASE_RESPONSE {
    ULONG64 Base;
    ULONG   Size;
} MODULE_BASE_RESPONSE, *PMODULE_BASE_RESPONSE;

#pragma pack(pop)
